### PR TITLE
Fixes #1642

### LINKED ISSUE #1642: Cannot set Custom RPC endpoint in ioPay Desktop
Trying to set a custom RPC endpoint in ioPay, this is what I tried:
```
http://my-gateway-ip:80
https://my-gateway-ip:443
http://my-gateway-ip:14014
https://my-gateway-ip:14014
```
where for `my-gateway-ip` I used the ip of remote node of mine (for which both ioctl and gRPC are working), localhost and 0.0.0.0 for a local node (still correctly working with ioctl and gRPC): none of the combinations above seems to work (see image). Even the official endpoint are not getting accepted:

image

### PR DESCRIPTION
**Pull request by ZQ-jhon**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind backend-change
> /kind ui-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by ZQ-jhon** [comment]
image
all of test cases are passed.

**Comment by ZQ-jhon** [comment]
image
seems working well.

**Review by uu-z — APPROVED** [review]

**Comment by uu-z** [comment]
please resolve conflict

**Comment by ZQ-jhon** [comment]
> please resolve conflict

resolved.

**Review by hunglmtb — APPROVED** [review]

**Pull request merged**
