### PR TITLE
Fixed #939: [wallet] cursor pointer for go back link

### LINKED ISSUE #939: [wallet] cursor pointer for go back link
Screen Shot 2019-08-06 at 12 02 24 PM

in both the deploy and interact with contracts

and this problem applies to all the <a> tag places

### PR DESCRIPTION
**Pull request by nmhung1210**
**What type of PR is this?**
bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #939 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by puncsky** [comment]
Screen Shot 2019-08-09 at 12 10 59 PM
please double check all places

**Comment by nmhung1210** [comment]
> Screen Shot 2019-08-09 at 12 10 59 PM
> please double check all places

I had to rechecked. And I'm not sure what do you mean for all tag places?

**Comment by puncsky** [comment]
please check all the other <a> tag and <Link> node places and see they have cursor pointer

**Comment by nmhung1210** [comment]
> please check all the other tag and node places and see they have cursor pointer

resolved

**Pull request merged**
