### PR TITLE
the dockerfile build a failure image

### PR DESCRIPTION
**Pull request by Fabryprog**
there was 2 errors
1. bug to copy line without final slash
2. dist folder missing with follow error

`2018-12-05T11:28:20.123Z - info: cannot load manifest: Error: Cannot find module '../../../dist/manifest.json'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at _callee$ (/app/src/lib/middleware/manifest-middleware.js:7:18)
at tryCatch (/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
at Generator.invoke [as _invoke] (/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
at Generator.prototype.(anonymous function) [as next] (/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
at step (/app/src/lib/middleware/manifest-middleware.js:10:191)
at /app/src/lib/middleware/manifest-middleware.js:10:437`

### CODE REVIEW

**Comment by puncsky** [comment]
Hi @Fabryprog, thanks for your fix. Please sign and the CLA, and then we would merge the PR :)

**Comment by Fabryprog** [comment]
@puncsky can you send me the CLA link? How to sign it?

**Comment by puncsky** [comment]
Oops... sorry that I thought you could see the link. Here it is -

https://cla-assistant.io/iotexproject/iotex-explorer?pullRequest=11

**Comment by Fabryprog** [comment]
I sign it!!

**Comment by puncsky** [comment]
thank you!

**Pull request merged**
